export default [
  {
    id: 1,
    name: "Pushups",
    sets: 3,
    reps: 10,
    weight: 0,
    image: "http://localhost:8080/images/Pushups.jpeg",
    date_id: 1,
  },
  {
    id: 2,
    name: "Barbell Full Squat",
    sets: 3,
    reps: 10,
    weight: 100,
    image: "http://localhost:8080/images/BarbellFullSquat.jpeg",
    date_id: 2,
  },
  {
    id: 3,
    name: "Barbell Bench Press",
    sets: 3,
    reps: 10,
    weight: 60,
    image: "http://localhost:8080/images/BarbellBenchPress.jpeg",
    date_id: 3,
  },
  {
    id: 4,
    name: "Barbell Deadlift",
    sets: 3,
    reps: 10,
    weight: 100,
    image: "http://localhost:8080/images/BarbellDeadlift.jpeg",
    date_id: 3,
  },
  {
    id: 5,
    name: "Shotgun row",
    sets: 3,
    reps: 10,
    weight: 60,
    image: "http://localhost:8080/images/ShotgunRow.jpeg",
    date_id: 4,
  },
  {
    id: 6,
    name: "Incline Hammer Curls",
    sets: 3,
    reps: 10,
    weight: 40,
    image: "http://localhost:8080/images/InclineHammerCurls.jpeg",
    date_id: 4,
  },
  {
    id: 7,
    name: "Bottoms Up",
    sets: 3,
    reps: 10,
    weight: 0,
    image: "http://localhost:8080/images/bottomsUp.jpeg",
    date_id: 5,
  },
  {
    id: 8,
    name: "Dumbbell V-Sit Cross Jab",
    sets: 3,
    reps: 10,
    weight: 100,
    image: "http://localhost:8080/images/DumbbellV-SitCrossJab.jpeg",
    date_id: 5,
  },
  {
    id: 9,
    name: "Chest dip",
    sets: 3,
    reps: 10,
    weight: 60,
    image: "http://localhost:8080/images/ChestDip.jpeg",
    date_id: 6,
  },
  {
    id: 10,
    name: "Pushups",
    sets: 3,
    reps: 10,
    weight: 0,
    image: "http://localhost:8080/images/Pushups.jpeg",
    date_id: 7,
  },
  {
    id: 11,
    name: "Barbell Full Squat",
    sets: 3,
    reps: 10,
    weight: 100,
    image: "http://localhost:8080/images/BarbellFullSquat.jpeg",
    date_id: 7,
  },
  {
    id: 12,
    name: "Barbell Bench Press",
    sets: 3,
    reps: 10,
    weight: 60,
    image: "http://localhost:8080/images/BarbellBenchPress.jpeg",
    date_id: 8,
  },
  {
    id: 13,
    name: "Barbell Deadlift",
    sets: 3,
    reps: 10,
    weight: 100,
    image: "http://localhost:8080/images/BarbellDeadlift.jpeg",
    date_id: 8,
  },
  {
    id: 14,
    name: "Shotgun row",
    sets: 3,
    reps: 10,
    weight: 60,
    image: "http://localhost:8080/images/ShotgunRow.jpeg",
    date_id: 9,
  },
  {
    id: 15,
    name: "Incline Hammer Curls",
    sets: 3,
    reps: 10,
    weight: 40,
    image: "http://localhost:8080/images/InclineHammerCurls.jpeg",
    date_id: 10,
  },
  {
    id: 16,
    name: "Bottoms Up",
    sets: 3,
    reps: 10,
    weight: 0,
    image: "http://localhost:8080/images/bottomsUp.jpeg",
    date_id: 10,
  },
  {
    id: 17,
    name: "Dumbbell V-Sit Cross Jab",
    sets: 3,
    reps: 10,
    weight: 100,
    image: "http://localhost:8080/images/DumbbellV-SitCrossJab.jpeg",
    date_id: 11,
  },
  {
    id: 18,
    name: "Chest dip",
    sets: 3,
    reps: 10,
    weight: 60,
    image: "http://localhost:8080/images/ChestDip.jpeg",
    date_id: 12,
  },
];
